# POST http://localhost:3000/portfolio/portfolio HTTP/1.1
# Content-Type: application/json

# {
#     "name": "Energy Stonks",
#     "exchange": "LSEG"
# }

# GET http://localhost:3000/portfolio/portfolio HTTP/1.1
# Content-Type: application/json

# GET http://localhost:3000/portfolio/asset/1 HTTP/1.1
# Content-Type: application/json

POST http://localhost:3000/portfolio/asset HTTP/1.1
Content-Type: application/json

{
    "portfolio_id": 1,
    "ticker": "HSBC",
    "quantity": 100
}

# router.patch("/asset", portfolioController.buySellOrder);

# PATCH http://localhost:3000/portfolio/asset HTTP/1.1
# Content-Type: application/json

# {
#     "portfolio_id": 1,
#     "ticker": "DEF",
#     "transaction_type": "sell",
#     "quantity": 10
# }
