POST http://localhost:3000/portfolioAsset/portfolioAsset HTTP/1.1
Content-Type: application/json

{
    "portfolio_id": 3,
    "ticker": "MSFT",
    "quantity": 25
}

# GET http://localhost:3000/portfolioAsset/portfolioAsset HTTP/1.1
# Content-Type: application/json

# DELETE http://localhost:3000/portfolioAsset/portfolioAsset/2 HTTP/1.1
# Content-Type: application/json
